# Generated by Django 5.2.12 on 2026-05-06 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_element_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='mainsite.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'character_favorite',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'character'), name='uniq_character_favorite_per_user')],
            },
        ),
    ]
