# Generated by Django 5.2.12 on 2026-05-07 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_characterfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_key', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=220)),
                ('section_title', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('watching', 'Watching'), ('seen', 'Seen')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timeline_progress',
                'ordering': ['section_title', 'title'],
                'constraints': [models.UniqueConstraint(fields=('user', 'timeline_key'), name='uniq_timeline_progress_per_user')],
            },
        ),
    ]
