# Generated by Django 5.2.12 on 2026-05-07 09:51

from django.db import migrations, models


def normalize_timeline_bookmarks(apps, schema_editor):
    TimelineProgress = apps.get_model("mainsite", "TimelineProgress")
    user_ids = TimelineProgress.objects.values_list("user_id", flat=True).distinct()

    for user_id in user_ids:
        items = list(TimelineProgress.objects.filter(user_id=user_id).order_by("-updated_at", "-id"))
        if not items:
            continue

        keep = items[0]
        TimelineProgress.objects.filter(user_id=user_id).exclude(pk=keep.pk).delete()
        keep.status = "bookmarked"
        keep.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_timelineprogress'),
    ]

    operations = [
        migrations.RunPython(normalize_timeline_bookmarks, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='timelineprogress',
            name='status',
            field=models.CharField(choices=[('bookmarked', 'Bookmarked')], max_length=20),
        ),
    ]
