# Generated by Django 5.2.12 on 2026-05-07 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_alter_timelineprogress_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timelineprogress',
            name='uniq_timeline_progress_per_user',
        ),
        migrations.AddConstraint(
            model_name='timelineprogress',
            constraint=models.UniqueConstraint(fields=('user',), name='uniq_timeline_bookmark_per_user'),
        ),
    ]
