# Generated by Django 6.0.3 on 2026-05-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mainsite",
            "0011_remove_timelineprogress_uniq_timeline_progress_per_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="admin_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("reviewed", "Reviewed"),
                    ("archived", "Archived"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
